# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

pool:
  vmImage: 'macOS-latest'

steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew' # string. Alias: wrapperScript. Required. Gradle wrapper. Default: gradlew.
    workingDirectory: '' 
    tasks: 'build' # string. Required. Tasks. Default: build.
 
  # JUnit Test Results
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml' # string.
    testRunTitle: # 'Test My App'
  
  # Code Coverage
    codeCoverageClassFilesDirectories: 'build/classes/main/'
  
  # Advanced
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    gradleOptions: '-Xmx1024m'
  

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
  displayName: Copy .apk files to artifact staging directory

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'
  displayName: Publish artifacts